### PR TITLE
Update tech.js

### PR DESCRIPTION
**Pull request by abhdhar-1618**
added Power BI in Design category and Microsoft Excel in Databases category

### CODE REVIEW

**Comment by abhdhar-1618** [comment]
added Power BI in Design category and Microsoft Excel in Databases category. Please Authorize the changes for the new additions.

**Comment by VishwaGauravIn** [comment]
Neither Power BI is a design tool nor MS Excel is a database.

**Comment by abhdhar-1618** [comment]
Okay.. can you add them to any of the groups you see fit?

**Comment by VishwaGauravIn** [comment]
Sure

**Comment by abhdhar-1618** [comment]
Thanks a lot..! @VishwaGauravIn

**Pull request closed without merging**
