### PR TITLE
feat: search functionality in tech stack

### PR DESCRIPTION
**Pull request by hyvip-ai**
#### Features:
 - Added search functionality
#### Fixes:
 - Added stack arrays in utils for reducing repetitive code
#### Component:
 - added a search components (styles added in global.css file)

### CODE REVIEW

**Comment by VishwaGauravIn** [comment]
@hyvip-ai Can you make a single search bar rather than different search bar for different section?

**Comment by hyvip-ai** [comment]
@VishwaGauravIn I can do it, but I will affect the UX part, user will not be able to understand, how that one search bar will work !
but if you still need it , I can do it.

**Comment by VishwaGauravIn** [comment]
I guess you can implement it by tweaking the UI a little. Try it

**Comment by VishwaGauravIn** [comment]
Breaking functionality

**Pull request closed without merging**
